//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Drawing.Design 
       // System.Windows.Forms.Design // .Resources 
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Forms.Design.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized Code Generation.
        /// </summary>
        internal static string DesignerOptions_CodeGenDisplay {
            get {
                return ResourceManager.GetString("DesignerOptions_CodeGenDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generation Settings.
        /// </summary>
        internal static string DesignerOptions_CodeGenSettings {
            get {
                return ResourceManager.GetString("DesignerOptions_CodeGenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InSitu Editing.
        /// </summary>
        internal static string DesignerOptions_EnableInSituEditingCat {
            get {
                return ResourceManager.GetString("DesignerOptions_EnableInSituEditingCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether InSitu editing is enabled..
        /// </summary>
        internal static string DesignerOptions_EnableInSituEditingDesc {
            get {
                return ResourceManager.GetString("DesignerOptions_EnableInSituEditingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable InSitu Editing.
        /// </summary>
        internal static string DesignerOptions_EnableInSituEditingDisplay {
            get {
                return ResourceManager.GetString("DesignerOptions_EnableInSituEditingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the default X and Y grid setting on designers when LayoutMode  = SnapToGrid..
        /// </summary>
        internal static string DesignerOptions_GridSizeDesc {
            get {
                return ResourceManager.GetString("DesignerOptions_GridSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Grid Cell Size.
        /// </summary>
        internal static string DesignerOptions_GridSizeDisplayName {
            get {
                return ResourceManager.GetString("DesignerOptions_GridSizeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Settings.
        /// </summary>
        internal static string DesignerOptions_LayoutSettings {
            get {
                return ResourceManager.GetString("DesignerOptions_LayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designer smart tag windows should be shown by default..
        /// </summary>
        internal static string DesignerOptions_ObjectBoundSmartTagAutoShow {
            get {
                return ResourceManager.GetString("DesignerOptions_ObjectBoundSmartTagAutoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Open Smart Tags.
        /// </summary>
        internal static string DesignerOptions_ObjectBoundSmartTagAutoShowDisplayName {
            get {
                return ResourceManager.GetString("DesignerOptions_ObjectBoundSmartTagAutoShowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Bound Smart Tag Settings.
        /// </summary>
        internal static string DesignerOptions_ObjectBoundSmartTagSettings {
            get {
                return ResourceManager.GetString("DesignerOptions_ObjectBoundSmartTagSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled optimized code generation.  Some controls may not be compatible with this mode.  For this change to take effect, Visual Studio must be closed and re-opened..
        /// </summary>
        internal static string DesignerOptions_OptimizedCodeGen {
            get {
                return ResourceManager.GetString("DesignerOptions_OptimizedCodeGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designers should display a sizing grid when LayoutMode = SnapToGrid..
        /// </summary>
        internal static string DesignerOptions_ShowGridDesc {
            get {
                return ResourceManager.GetString("DesignerOptions_ShowGridDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        internal static string DesignerOptions_ShowGridDisplayName {
            get {
                return ResourceManager.GetString("DesignerOptions_ShowGridDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designers should snap to grid dots when LayoutMode = SnapToGrid..
        /// </summary>
        internal static string DesignerOptions_SnapToGridDesc {
            get {
                return ResourceManager.GetString("DesignerOptions_SnapToGridDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to Grid.
        /// </summary>
        internal static string DesignerOptions_SnapToGridDisplayName {
            get {
                return ResourceManager.GetString("DesignerOptions_SnapToGridDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designers should show smart tag popup windows..
        /// </summary>
        internal static string DesignerOptions_UseSmartTags {
            get {
                return ResourceManager.GetString("DesignerOptions_UseSmartTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designers should use snap lines.  If true, snap lines will be used as guides.  If false, grid lines will be used..
        /// </summary>
        internal static string DesignerOptions_UseSnapLines {
            get {
                return ResourceManager.GetString("DesignerOptions_UseSnapLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This IDataObject doesn&apos;t support SetData..
        /// </summary>
        internal static string DragDropSetDataError {
            get {
                return ResourceManager.GetString("DragDropSetDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method/object is not implemented by design..
        /// </summary>
        internal static string NotImplementedByDesign {
            get {
                return ResourceManager.GetString("NotImplementedByDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winforms Designer is not supported on this platform..
        /// </summary>
        internal static string PlatformNotSupported_WinformsDesigner {
            get {
                return ResourceManager.GetString("PlatformNotSupported_WinformsDesigner", resourceCulture);
            }
        }
    }
}
